[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "devsarvesh92", email = "sarveshdev92@gmail.com"},
]
dependencies = [
    "fastapi>=0.92.0",
    "uvicorn>=0.20.0",
    "boto3>=1.26.84",
]
requires-python = ">=3.11"
license = {text = "MIT"}
